### ISSUE TITLE
Handling errors on (on saving row) function

### ISSUE THREAD

**Issue by AihamAbuRafaa** [noam-honig/radweb#18]

**Comment by noam-honig** [comment]
I recommend using a general angular error handler - as used in the remult code sample - see the app-routing.module.ts code for this:

**Comment by noam-honig** [comment]
I've just updated a bit the error handling to ignore duplicate errors
https://github.com/noam-honig/radweb/blob/ba9c40199b4349879932bdeae9c76baae033ed53/projects/core/schematics/hello/files/src/app/common/dialog.ts#46
